// utils/generateCertificate.js
/*const PDFDocument = require('pdfkit');
const fs = require('fs');

const generateCertificate = (learnerName, score, filename) => {
  const doc = new PDFDocument();
  doc.pipe(fs.createWriteStream(filename));

  doc.fontSize(20).text('Certificate of Completion', { align: 'center' });
  doc.fontSize(14).text(`This certifies that ${learnerName} has successfully completed the exam with a score of ${score}`, {
    align: 'center',
  });

  doc.end(); 
};

module.exports = generateCertificate;*/
import jsPDF from 'jspdf';

const generateCertificate = (studentName, score) => {
  // Create a new jsPDF instance
  const doc = new jsPDF();

  // Set the font for the certificate text (you can customize this)
  doc.setFont('times', 'normal');
  doc.setFontSize(16);

  // Add title to the certificate
  doc.text('Certificate of Completion', 105, 40, null, null, 'center');

  // Add student's name to the certificate
  doc.setFontSize(12);
  doc.text(`This is to certify that`, 105, 60, null, null, 'center');
  doc.setFontSize(14);
  doc.text(studentName, 105, 80, null, null, 'center');

  // Add score to the certificate
  doc.setFontSize(12);
  doc.text(`has successfully completed the exam with a score of:`, 105, 100, null, null, 'center');
  doc.setFontSize(14);
  doc.text(`${score}%`, 105, 120, null, null, 'center');

  // Optionally add a footer or more details
  doc.setFontSize(10);
  doc.text('Generated by AI-Proctored Exam System', 105, 140, null, null, 'center');
  
  // Save the generated PDF with the student's name
  doc.save(`${studentName}_certificate.pdf`);
};

export default generateCertificate;

